apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.appname }}-pdb
spec:
  minAvailable: {{ .Values.autoscaling.minAvailable }}
  selector:
    matchLabels:
      version: {{ .Values.label.version }}
