apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.appname }}-pdb
  labels:
    app: {{ .Values.label.app }}
spec:
  minAvailable: {{ .Values.autoscaling.minAvailable }}
  selector:
    matchLabels:
      version: {{ .Values.label.version }}
