apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}-svc
  labels:
    app: {{ .Values.label.app }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    version: {{ .Values.label.version }}
    app: {{ .Values.label.app }}
