apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}-v2
  labels:
    app: {{ .Values.label.app }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      version: {{ .Values.label.version2 }}
      app: {{ .Values.label.app }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        version: {{ .Values.label.version2 }}
        app: {{ .Values.label.app }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.appname }}-sa-v2
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: {{ .Values.env.name2 }}
              value: {{ .Values.env.value2 }}
            - name: {{.Values.postgres_env.key1 }}
              value: {{ .Values.postgres_env.value1 }}
            - name: {{.Values.postgres_env.key2 }}
              value: {{ .Values.postgres_env.value2 }}
            - name: {{.Values.postgres_env.key3 }}
              value: {{ .Values.postgres_env.value3 }}
            - name: {{.Values.postgres_env.key4 }}
              value: {{ .Values.postgres_env.value4 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- if .Values.probe.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
  minReadySeconds: {{ .Values.minReadySeconds }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
